version: '3.8'
services:
  pgdb:
    image: postgres:14.1-alpine
    container_name: pgdb_container
    restart: always
    environment:
      - POSTGRES_DB=click_stream
      - POSTGRES_USER=user_a
      - POSTGRES_PASSWORD=pwd_a
    ports:
      - '5454:5432'
    volumes: 
      - db-data:/opt/dbdata/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    depends_on: [pgdb]
    container_name: pgadmin_container
    restart: always
    ports:
      - "8088:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user_a@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: pwd_a
    volumes:
      - pgadmin-data:/opt/dbdata/pgadmin/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.5
    container_name: zookeeper_container
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.3.5
    container_name: kafka_container
    restart: on-failure
    depends_on: [zookeeper]
    environment:
      KAFKA_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
    - 29092:29092


  debezium:
    image: debezium/connect:2.4
    container_name: debezium_container
    restart: on-failure
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      STATUS_STORAGE_TOPIC: connect_statuses
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    depends_on: [pgdb, kafka]
    links: 
      - zookeeper
      - pgdb
    ports:
      - 8083:8083
      

    # ELK
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elastic_container
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: on-failure
    networks:
      - elastic_net
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: false
    
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana_container
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    volumes:
      - kibana-data:/usr/share/kibana/data
    restart: on-failure
    networks:
      - elastic_net
    environment:
      ELASTICSEARCH_HOSTS: 'http://elastic_container:9200'

volumes:
  db-data:
    driver: local
  pgadmin-data:
    driver: local
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local

networks:
  elastic_net:
    driver: bridge 
  